language: bash

cache:
  directories:
    - $HOME/.gradle

env:
  global:
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - JDK="adopt@1.8"

before_install:
  - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
  - source ~/.install-jdk-travis.sh

before_script:
  - chmod +x gradlew

script: ./gradlew check --console=plain

deploy:
  provider: script
  script: ./gradlew bintrayUpload --console=plain
  skip_cleanup: true
  on:
    branch: master
    tags: true